export const events = [
  {
    id: 1,
    title: "Tech Innovation Summit 2024",
    date: "March 15, 2024",
    location: "San Francisco, CA",
    description: "Join industry leaders for a day of cutting-edge technology discussions and networking.",
    fullDescription:
      "The Tech Innovation Summit brings together the brightest minds in technology to discuss the future of innovation. This full-day event features keynote speakers from major tech companies, interactive workshops, and extensive networking opportunities. Topics include AI, blockchain, cybersecurity, and emerging technologies that will shape our future.",
    category: "Technology",
    price: 299,
    attendees: 1250,
    duration: "8 hours",
    organizer: "TechEvents Inc.",
  },
  {
    id: 2,
    title: "Jazz Under the Stars",
    date: "April 22, 2024",
    location: "New York, NY",
    description: "An enchanting evening of smooth jazz music in Central Park's outdoor amphitheater.",
    fullDescription:
      "Experience the magic of jazz music under the starlit sky in one of New York's most beautiful venues. This outdoor concert features renowned jazz musicians performing classic and contemporary pieces. Bring a blanket and enjoy food trucks offering gourmet options. Perfect for date nights or music enthusiasts looking for a unique cultural experience.",
    category: "Music",
    price: 75,
    attendees: 800,
    duration: "4 hours",
    organizer: "NYC Jazz Society",
  },
  {
    id: 3,
    title: "Startup Pitch Competition",
    date: "May 8, 2024",
    location: "Austin, TX",
    description: "Watch emerging startups pitch their innovative ideas to top investors and win funding.",
    fullDescription:
      "The ultimate startup showcase where entrepreneurs present their groundbreaking ideas to a panel of seasoned investors and industry experts. This high-energy event features 20 carefully selected startups competing for funding and mentorship opportunities. Attendees will witness the next generation of business innovation and have networking opportunities with founders, investors, and fellow entrepreneurs.",
    category: "Business",
    price: 150,
    attendees: 500,
    duration: "6 hours",
    organizer: "Startup Austin",
  },
  {
    id: 4,
    title: "Food & Wine Festival",
    date: "June 12, 2024",
    location: "Napa Valley, CA",
    description: "Savor exquisite cuisine and premium wines from renowned chefs and vintners.",
    fullDescription:
      "Indulge in a culinary journey through Napa Valley's finest offerings. This premium food and wine festival features tastings from award-winning wineries, cooking demonstrations by celebrity chefs, and exclusive dining experiences. Learn about wine pairing, sustainable farming practices, and the art of fine dining in one of the world's most beautiful wine regions.",
    category: "Food & Drink",
    price: 225,
    attendees: 600,
    duration: "5 hours",
    organizer: "Napa Events Co.",
  },
  {
    id: 5,
    title: "Digital Marketing Masterclass",
    date: "July 18, 2024",
    location: "Chicago, IL",
    description: "Learn advanced digital marketing strategies from industry experts and grow your business.",
    fullDescription:
      "Master the art of digital marketing with this comprehensive workshop designed for business owners, marketers, and entrepreneurs. Topics include social media strategy, content marketing, SEO optimization, email marketing, and analytics. Hands-on sessions, case studies, and networking with fellow marketers make this an invaluable learning experience.",
    category: "Education",
    price: 199,
    attendees: 300,
    duration: "7 hours",
    organizer: "Marketing Pro Academy",
  },
  {
    id: 6,
    title: "Outdoor Adventure Expo",
    date: "August 25, 2024",
    location: "Denver, CO",
    description: "Discover the latest in outdoor gear and adventure travel destinations.",
    fullDescription:
      "The ultimate gathering for outdoor enthusiasts featuring the latest gear, adventure travel destinations, and expert-led workshops. Try out new equipment, learn survival skills, plan your next adventure, and connect with fellow outdoor lovers. Features include rock climbing walls, gear testing areas, and presentations from world-renowned adventurers.",
    category: "Sports & Recreation",
    price: 45,
    attendees: 2000,
    duration: "8 hours",
    organizer: "Adventure Seekers",
  },
  {
    id: 7,
    title: "Art Gallery Opening Night",
    date: "September 14, 2024",
    location: "Los Angeles, CA",
    description: "Exclusive preview of contemporary art exhibition featuring emerging and established artists.",
    fullDescription:
      "Join us for an elegant evening celebrating contemporary art at one of LA's premier galleries. This exclusive opening features works from both emerging and established artists, with pieces ranging from paintings and sculptures to digital installations. Enjoy wine, hors d'oeuvres, and the opportunity to meet the artists and discuss their creative processes.",
    category: "Arts & Culture",
    price: 85,
    attendees: 400,
    duration: "4 hours",
    organizer: "Modern Art Gallery",
  },
  {
    id: 8,
    title: "Wellness & Mindfulness Retreat",
    date: "October 5, 2024",
    location: "Sedona, AZ",
    description: "Rejuvenate your mind and body with yoga, meditation, and holistic wellness practices.",
    fullDescription:
      "Escape to the serene red rocks of Sedona for a transformative wellness experience. This day-long retreat includes guided meditation sessions, yoga classes for all levels, sound healing, and workshops on mindful living. Healthy, organic meals are provided, and you'll leave with practical tools for maintaining wellness in your daily life.",
    category: "Health & Wellness",
    price: 175,
    attendees: 150,
    duration: "8 hours",
    organizer: "Sedona Wellness Center",
  },
]
